# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  #Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      
  #Docker 
  - package-ecosystem: "docker" 
    directory: "/" 
    schedule:
      interval: "daily"
      
  #Github Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
