version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - kanban-network
    restart: unless-stopped
  kanban:
    build: .
    container_name: kanban
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres_container:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=changeme
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - kanban-network

networks:
  kanban-network:

volumes:
  postgres: